//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.11 at 08:22:27 PM BST 
//


package com.magmanics.licensing.ws.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://magmanics.com/licensing/ws/model}serial"/>
 *         &lt;element ref="{http://magmanics.com/licensing/ws/model}hardwareIdentifier"/>
 *         &lt;element ref="{http://magmanics.com/licensing/ws/model}extraInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serial",
    "hardwareIdentifier",
    "extraInfo"
})
@XmlRootElement(name = "ActivationRequest")
public class ActivationRequest
    implements ToString
{

    @XmlElement(required = true)
    protected String serial;
    @XmlElement(required = true)
    protected String hardwareIdentifier;
    @XmlElement(required = true)
    protected Map extraInfo;

    /**
     * Gets the value of the serial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerial() {
        return serial;
    }

    /**
     * Sets the value of the serial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerial(String value) {
        this.serial = value;
    }

    /**
     * Gets the value of the hardwareIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHardwareIdentifier() {
        return hardwareIdentifier;
    }

    /**
     * Sets the value of the hardwareIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHardwareIdentifier(String value) {
        this.hardwareIdentifier = value;
    }

    /**
     * Gets the value of the extraInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Map }
     *     
     */
    public Map getExtraInfo() {
        return extraInfo;
    }

    /**
     * Sets the value of the extraInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Map }
     *     
     */
    public void setExtraInfo(Map value) {
        this.extraInfo = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theSerial;
            theSerial = this.getSerial();
            strategy.appendField(locator, this, "serial", buffer, theSerial);
        }
        {
            String theHardwareIdentifier;
            theHardwareIdentifier = this.getHardwareIdentifier();
            strategy.appendField(locator, this, "hardwareIdentifier", buffer, theHardwareIdentifier);
        }
        {
            Map theExtraInfo;
            theExtraInfo = this.getExtraInfo();
            strategy.appendField(locator, this, "extraInfo", buffer, theExtraInfo);
        }
        return buffer;
    }

}
