//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.11 at 08:22:27 PM BST 
//


package com.magmanics.licensing.ws.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.magmanics.licensing.ws.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HardwareIdentifier_QNAME = new QName("http://magmanics.com/licensing/ws/model", "hardwareIdentifier");
    private final static QName _ExtraInfo_QNAME = new QName("http://magmanics.com/licensing/ws/model", "extraInfo");
    private final static QName _Serial_QNAME = new QName("http://magmanics.com/licensing/ws/model", "serial");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.magmanics.licensing.ws.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MapEntry }
     * 
     */
    public MapEntry createMapEntry() {
        return new MapEntry();
    }

    /**
     * Create an instance of {@link Map }
     * 
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link ActivationRequest }
     * 
     */
    public ActivationRequest createActivationRequest() {
        return new ActivationRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://magmanics.com/licensing/ws/model", name = "hardwareIdentifier")
    public JAXBElement<String> createHardwareIdentifier(String value) {
        return new JAXBElement<String>(_HardwareIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Map }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://magmanics.com/licensing/ws/model", name = "extraInfo")
    public JAXBElement<Map> createExtraInfo(Map value) {
        return new JAXBElement<Map>(_ExtraInfo_QNAME, Map.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://magmanics.com/licensing/ws/model", name = "serial")
    public JAXBElement<String> createSerial(String value) {
        return new JAXBElement<String>(_Serial_QNAME, String.class, null, value);
    }

}
